language: python

matrix:
    fast_finish: true
    include:
        - os: linux
          dist: bionic
          sudo: required
          python: 3.6
        - os: linux
          dist: bionic
          sudo: required
          python: 3.7
        - os: linux
          dist: bionic
          sudo: required
          python: 3.8


install:
    - pip install --upgrade pip setuptools wheel
    - pip install coveralls codecov pyflakes
    - pip install --only-binary=numpy numpy
    - pip install -r requirements.txt
    - pip install git+https://github.com/dvolgyes/dcm2hdr

script:
  - make ci-test
  - make test

after_success:
  - coveralls
  - codecov
