language: python

matrix:
    fast_finish: true
    include:
        - os: linux
          dist: trusty
          sudo: required
          python: 3.5
          env: PYVERSION="3"

        - os: linux
          dist: trusty
          sudo: required
          python: 3.6
          env: PYVERSION="3"

        - os: linux
          dist: trusty
          sudo: required
          python: 2.7
          env: PYVERSION="2"

install:
    - pip${PYVERSION} install --upgrade pip setuptools wheel
    - pip${PYVERSION} install coveralls codecov pyflakes
    - pip${PYVERSION} install --only-binary=numpy numpy
    - pip${PYVERSION} install -r requirements.txt
    - pip${PYVERSION} install git+https://github.com/dvolgyes/dcm2hdr

script:
  - make ci-test
  - make test

after_success:
  - coveralls
  - codecov
